### ISSUE TITLE
프로젝트 기초 세팅

### ISSUE THREAD

**Issue by amourxyoung** [Team-Growthook/Growthook-AOS-Laboratory#1]
## 📌 TODO
- [x] git ignore 설정
- [x] issue / pr 템플릿 추가
- [ ] 슬랙 연동하기
- [ ] CI 구축
- [x] gradle dependency 추가
- [ ] manifest 설정 (인터넷 권한 추가, 가로모드 방지)
- [x] util 추가
- [x] mvvm 폴더링 기초세팅
