### ISSUE TITLE
홈화면 기능 연습

### ISSUE THREAD

**Issue by amourxyoung** [Team-Growthook/Growthook-AOS-Laboratory#2]
## 📌 TODO
- [x] 바텀 네비게이션 추가
- [ ] 리사이클러뷰 아이템 xml 구현
- [ ] 어댑터 생성 및 연결
- [x] 바텀시트 xml 구현
- [x] 아이템 클릭시 바텀시트 뜨게하기
