### ISSUE TITLE
리사이클러뷰 다중 선택

### ISSUE THREAD

**Issue by gaeun5744** [Team-Growthook/Growthook-AOS-Laboratory#3]
## 📌 TODO
- [ ] 리사이클러뷰 다중 선택
- [ ] 버튼 클릭 시 선택 해제
- [ ] 선택된 숫자 표시
